# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mizar
email:198844727@qq.com
description: 爱着开阳的暗淡之人栖息地
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: linjianuta
github_username:linjianuta
paginate: 5
theme-dark: false #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
